# add ~/.bash_profile if needed for executing ~/.bashrc
###
 # @Author: yoren
 # @Date: 2023-04-29 10:31:24
 # @LastEditTime: 2023-04-29 10:31:28
 # @FilePath: \materiald:\黄轩宇\hexo + butterfly博客\source\_posts\bash_profile.sh
 # @Tips: 纵使前路黑暗，也有可以照亮你的星光，而你自身就是光
### 
if [ -e ~/.bashrc -a ! -e ~/.bash_profile -a ! -e ~/.bash_login -a ! -e ~/.profile ]; then
  printf "\n\033[31mWARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.\033[m\n\n"
  echo "This looks like an incorrect setup."
  echo "A ~/.bash_profile that loads ~/.bashrc will be created for you."
  cat >~/.bash_profile <<-\EOF
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc
	EOF
fi

export HEXO_ALGOLIA_INDEXING_KEY=5cb803d644bd0c9e349ca3777d104cf3